In [47]:
import numpy as np

In [48]:
np.random.random()

0.12939582494933521

In [49]:
np.random.seed(12)    #you will get the same random numbers evrytime
a=np.random.random(3)
a

array([0.15416284, 0.7400497 , 0.26331502])

In [50]:
np.random.random(5)     # you will get an array of 5 random numbers.

array([0.53373939, 0.01457496, 0.91874701, 0.90071485, 0.03342143])

In [51]:
np.random.uniform(3,10)      #you get random float numbers between (3-10)

9.698645353925818

In [52]:
np.random.uniform(1,100,10)   # you get 10 random numbers between (1-100)

array([14.58372281, 29.09900694, 61.00223525, 94.47828847, 85.42081857,
        1.22366412, 52.60137669, 55.65172569, 49.05236395, 77.04528125])

In [53]:
np.random.uniform(1,100,10).reshape(2,5)

array([[16.91095856, 76.69148458,  3.06017   , 14.38580766, 12.51102872],
       [31.67986086, 67.47381188, 47.65174805, 81.80066151, 29.66909157]])

In [54]:
np.random.randint(1,10)   # integer instead of float

2

In [69]:
b=np.random.randint(1,10,5)
b

array([6, 1, 7, 7, 4], dtype=int32)

In [70]:
np.max(b)

np.int32(7)

In [71]:
np.min(b)

np.int32(1)

In [76]:
np.argmax(b)   # returns the index

np.int64(2)

In [77]:
np.argmin(b)

np.int64(1)

In [124]:
int(b[np.argmax(b)])

7

In [123]:
int(b[np.argmin(b)])

1

In [82]:
x = np.random.randint(1,10,6)
x

array([3, 7, 5, 8, 7, 3], dtype=int32)

In [83]:
x[x%2==1]=-1
x

array([-1, -1, -1,  8, -1, -1], dtype=int32)

In [93]:
np.where(x%2==1,-1,x)
# If condition is True, replace with -1; else keep the value

array([-1, -1, -1,  8, -1, -1], dtype=int32)

In [108]:
arr = np.array([1,4,3,2,5])
arr

array([1, 4, 3, 2, 5])

In [125]:
arr=np.sort(arr)
arr

array([1, 2, 3, 4, 5])

In [126]:
np.percentile(arr,[25,75])

array([2., 4.])

In [127]:
i=int(np.percentile(arr,50))
i

3