In [2]:
import numpy as np

### concatenate

In [3]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [4]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

### indexing and slicing

In [5]:
data = np.array([1,2,3,4,5])
int(data[1])

2

In [6]:
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2]
[2 3 4 5]
[4 5]


In [7]:
a1 = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [8]:
print(a1[a1 < 7])

[1 2 3 4 5 6]


In [9]:
divisible_by_2 = a1[a1%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


you can also use "&" and "|" logical operators

In [10]:
c = (a>2) & (a<10)
c

array([False, False,  True,  True])

In [11]:
c=a[(a>2) & (a<10)]
print(c)

[3 4]


In [12]:
f = (a>5) | (a==5)
print(f)

[False False False False]


In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

### How to create an array from existing data

In [14]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [15]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [16]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

**spliting array**

In [17]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [18]:
np.hsplit(x, 3)   # (data, into 3 equal parts)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [19]:
np.hsplit(x, (3, 4))   #(data, (split array after 'third' and 'sixth' col))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

### Basic Operations

In [20]:
b = np.array([[1, 1], [2, 2]])

You can sum over the axis of rows with:

In [21]:
b.sum(axis=0)

array([3, 3])

You can sum over the axis of columns with

In [22]:
b.sum(axis=1)

array([2, 4])

In [23]:
import pandas as pd

In [24]:
data=pd.DataFrame({'a':[1,2,3],
                   'b':[4,5,6],
                   'c':[7,8,9]})
data

a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

### Unique items and counts

In [26]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [ ]:
a_unique = np.unique(a)