### 1. Import the numpy package under the name np

In [2]:
import numpy as np

### 2. Print the numpy 'Version' and the 'Configuration' 

In [7]:
print(np.__version__)
np.show_config()

2.1.1
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-jy1pqop7/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-jy1pqop7/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy/numpy/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-jy1pqop7/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-jy1pqop7/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.

### 3. Create a null vector of size 10

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 4. How to find the memory size of any array

In [13]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [14]:
# or
Z.nbytes

800

### 5. How to get the documentation of the numpy add function from the command line? 

In [18]:
# %run 'python -c "import numpy; numpy.info(numpy.add)"'

### 6. Create a null vector of size 10 but the fifth value which is 1

In [20]:
x = np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### 7. Create a vector with values ranging from 10 to 49 


In [22]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 8. Reverse a vector (first element becomes last)

In [23]:
x = np.arange(50)
x=x[::-1]
x

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [68]:
j=np.arange(9).reshape(3,3)
j

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [45]:
j=np.nonzero(a)   #return a tuple of indices
print(j)

(array([0, 1, 4]),)


In [75]:
# or
a = np.array([1, 2, 0, 0, 4, 0])
print([a!=0])
print(a[a!=0])

[array([ True,  True, False, False,  True, False])]
[1 2 4]


### 11. Create a 3x3 identity matrix

In [80]:
np.identity(3)
# or
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 12. Create a 3x3x3 array with random values

In [82]:
np.random.random((3,3,3))

array([[[0.05201674, 0.93655794, 0.96685124],
        [0.39045435, 0.97972965, 0.02711556],
        [0.70915995, 0.33171281, 0.37166649]],

       [[0.35922056, 0.44494909, 0.74817625],
        [0.36936013, 0.65469488, 0.12838081],
        [0.88402868, 0.20357505, 0.69298925]],

       [[0.28614958, 0.33780373, 0.52573384],
        [0.93131253, 0.21089569, 0.82597811],
        [0.20769694, 0.91672815, 0.01970053]]])

### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [88]:
a=np.random.random((10,10))
a

array([[0.02191267, 0.28987752, 0.89029302, 0.6455016 , 0.4921898 ,
        0.70392945, 0.25755266, 0.60248421, 0.06813191, 0.28045426],
       [0.91632255, 0.30129484, 0.92213445, 0.68830271, 0.84272543,
        0.00878452, 0.12192723, 0.30326963, 0.18902444, 0.02497228],
       [0.99223954, 0.36305563, 0.24873714, 0.06445605, 0.09747721,
        0.95978816, 0.42580858, 0.8187029 , 0.26729688, 0.32242767],
       [0.82446834, 0.12245516, 0.89131615, 0.80249224, 0.4877299 ,
        0.2783142 , 0.50013361, 0.98014204, 0.66006959, 0.81089839],
       [0.45651802, 0.72632386, 0.789174  , 0.39171212, 0.59675902,
        0.35158313, 0.9020126 , 0.70424016, 0.99216893, 0.56863638],
       [0.2048987 , 0.94801817, 0.47700591, 0.46213099, 0.27998191,
        0.43762251, 0.25599422, 0.55431001, 0.02448213, 0.2583291 ],
       [0.17186108, 0.88025696, 0.00838315, 0.81231907, 0.91499578,
        0.29666552, 0.20097827, 0.09199909, 0.55338756, 0.1817113 ],
       [0.43823522, 0.61773984, 0.7729850

In [93]:
a.max()

np.float64(0.9922395438660558)

In [121]:
a.min()

np.float64(0.008383152404961347)

### 14. Create a random vector of size 30 and find the mean value

In [122]:
x=np.random.random(30)
np.mean(x)

np.float64(0.4567626188170462)

### 15. Create a 2d array with 1 on the border and 0 inside

In [123]:
x = np.ones((10,10))
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### 16. How to add a border (filled with 0's) around an existing array?

In [124]:
k = np.random.randint(0,10,size=(5,5))
k[[0,-1],:]=0
k[:,[0,-1]]=0
print(k)

# or

np.pad()

[[0 0 0 0 0]
 [0 7 6 2 0]
 [0 2 7 1 0]
 [0 9 8 9 0]
 [0 0 0 0 0]]


TypeError: pad() missing 2 required positional arguments: 'array' and 'pad_width'

### 17. What is the result of the following expression?

In [125]:
0 * np.nafenp.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

AttributeError: module 'numpy' has no attribute 'nafenp'

### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [152]:
arr1=np.random.randint(1,25,25).reshape(5,5)
arr1

array([[ 1, 14, 12, 14,  3],
       [ 8, 14, 12, 14,  1],
       [10, 22,  4, 13, 23],
       [12, 14,  3, 18,  2],
       [18, 23, 17, 17,  7]], dtype=int32)

In [151]:
np.diag(arr1,k=-1)

array([17, 16,  6,  6], dtype=int32)

In [145]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [162]:
x = np.zeros((8,8),dtype=int)
x[1::2,1::2]=1
x[::2,::2]=1
x

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the    100th element? 

In [168]:
np.unravel_index(99,(6,7,8))

x = np.unravel_index(99,(6,7,8))
result = tuple(int(i) for i in x)
result

(1, 5, 3)

### 21. Create a checkerboard 8x8 matrix using the tile function

In [169]:
arr1 = np.array([[1,0],
                 [0,1]])
np.tile(arr1,(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

### 22. Normalize a 5x5 random matrix

normalized = arr - min(arr) / max(arr) - min(arr)

std_deviation = max(arr) - min(arr)

In [180]:
arr = np.random.randint(1,26,25).reshape(5,5)
normalized =(arr - np.mean (arr)) / (np.std (arr))
print(normalized)

[[-0.89104211  1.46759877 -0.89104211 -1.41518453 -0.4979353 ]
 [-0.10482848  1.59863438  0.28827833  1.33656317  0.41931393]
 [ 0.68138514 -1.28414892  0.15724273  0.02620712  1.07449196]
 [ 1.72966998 -1.28414892 -1.15311332  1.20552756 -1.15311332]
 [-0.36689969  0.15724273 -1.41518453 -0.10482848  0.41931393]]


### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [181]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [184]:
a = np.dot(np.ones((5,3)),np.ones((3,2)))
a

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [191]:
arr2 = np.arange(11)
arr2[(3<arr2) & (arr2<8)] = -arr2[(3<arr2) & (arr2<8)]
arr2

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

### 26. What is the output of the following script?

. print(sum(range(5),-1))

. from numpy import *

. print(sum(range(5),-1))

In [192]:
print(sum(range(5),-1))

9
